version: '3.8'

services:
  security-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/security_service
      - ENVIRONMENT=development
      - AUTH_BYPASS=true
      - AUTH_BYPASS_SECRET=dev-bypass-secret
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=security_service
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
