name: Update API Reference

on:
  push:
    paths:
      - 'backend/*/api/openapi.yaml'
      - 'backend/*/api/asyncapi.yaml'
  workflow_dispatch:  # Allow manual triggers

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm install -g redoc-cli
          npm install -g @asyncapi/generator
          pip install mkdocs-material
      
      - name: Validate OpenAPI specifications
        run: |
          for spec in $(find backend -name "openapi.yaml"); do
            echo "Validating $spec"
            npx swagger-cli validate $spec
          done
      
      - name: Validate AsyncAPI specifications
        run: |
          for spec in $(find backend -name "asyncapi.yaml"); do
            echo "Validating $spec"
            npx @asyncapi/validator $spec
          done
      
      - name: Generate service documentation
        run: |
          mkdir -p docs/api/services
          
          # Generate HTML docs for each service
          for spec in $(find backend -name "openapi.yaml"); do
            service_name=$(echo $spec | cut -d/ -f2)
            output_dir="docs/api/services/${service_name}"
            mkdir -p $output_dir
            
            echo "Generating docs for ${service_name}"
            redoc-cli bundle -o "${output_dir}/index.html" $spec
          done
      
      - name: Update API index
        run: node scripts/generate-api-index.js
      
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs/api'
          message: 'Auto-update API documentation'
          default_author: github_actions
